# Generated by Django 3.2 on 2022-12-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_comentario_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
